{% set name = "sunpy" %}
{% set version = "4.0.4" %}
{% set sha256 = "3b8563c5cb895605238f3dd55b27330a3271bc9bc02fde0c0671ac467e782dde" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}  # [not win]
  host:
    - python
    - pip
    - setuptools_scm
    - extension-helpers
    - numpy
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - asdf >=2.8.0
    - asdf-astropy >=0.1.1
    - astropy >=4.1.0
    - scipy >=1.3.0
    - matplotlib-base >=3.2.0
    - pandas >=1.0.0
    - parfive >=1.2.0
    - sqlalchemy >=1.3.4
    - scikit-image >=0.16.0
    - glymur >=0.8.18,!=0.9.0,!=0.9.5
    - beautifulsoup4 >=4.8.0
    - drms >=0.6.1
    - python-dateutil >=2.8.0
    - zeep >=3.4.0
    - tqdm >=4.32.1
    - h5netcdf >=0.8.1
    - h5py >=3.1.0 # Not a direct dependancy, but goes files wont load without
    - mpl_animators >=1.0.0
    - cdflib >=0.3.19,!=0.4.0
    - reproject

test:
  requires:
    - hypothesis
    - pytest-astropy
    - pytest-mock
    - pytest-xdist
    - asdf !=2.10.0
    - jplephem
    - pytest-mpl
    - reproject
    - cdflib
  imports:
    - sunpy
    - sunpy.cm
    - sunpy.coordinates
    - sunpy.data
    - sunpy.database
    - sunpy.image
    - sunpy.instr
    - sunpy.io
    - sunpy.map
    - sunpy.map.sources
    - sunpy.net
    - sunpy.net.hek
    - sunpy.net.hek2vso
    - sunpy.net.helio
    - sunpy.net.jsoc
    - sunpy.net.vso
    - sunpy.physics
    - sunpy.roi
    - sunpy.sun
    - sunpy.tests
    - sunpy.time
    - sunpy.timeseries
    - sunpy.timeseries.sources
    - sunpy.util
    - sunpy.visualization

about:
  home: https://www.sunpy.org/
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: SunPy is an open-source Python library for Solar Physics data analysis and visualization.
  license_family: BSD
  dev_url: https://github.com/sunpy/sunpy

extra:
  recipe-maintainers:
    - cadair
    - wtbarnes
    - nabobalis
    - dstansby
