{% set name = "sunpy" %}
{% set version = "7.0.1" %}
{% set sha256 = "f59086f42b53a6018696ab57725d9ea5107315c6d5bc833365c5e4e42439ffe0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<311]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}  # [not win]
    - {{ stdlib("c") }}    # [not win]
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - extension-helpers
    - numpy
  run:
    - python
    - sqlite !=3.49.0,!=3.49.1  # https://github.com/conda-forge/sqlite-feedstock/issues/130
    # base
    - astropy-base >=6.1.0
    - numpy >=1.25.0
    - packaging >=23.2
    - parfive >=2.1.0
    - pyerfa >=2.0.1.1
    - requests >=2.32.0
    - fsspec >=2023.6.0
    # asdf
    - asdf >=3.0.0
    - asdf-astropy >=0.5.0
    # image
    - scipy >=1.11.0
    # jpeg2000
    - glymur >=0.13.0
    - lxml >=4.9.1,!=5.0.0
    # map
    - contourpy >=1.1.0
    - matplotlib-base >=3.8.0
    - mpl_animators >=1.2.0
    - reproject >=0.12.0
    # net
    - beautifulsoup4 >=4.13.0
    - drms >=0.7.1
    - python-dateutil >=2.9.0
    - tqdm >=4.66.0
    - zeep >=4.3.0
    # spice
    - spiceypy >=6.0.0  # [not ppc64le]
    # timeseries
    - cdflib >=1.3.2
    - h5netcdf >=1.2.0
    - h5py >=3.9.0 # Not a direct dependancy, but goes files wont load without
    - pandas >=2.1.0

test:
  requires:
    - hvpy
    - hypothesis
    - jplephem
    - scikit-image
    - libopencv * headless*               # [unix]
    - opencv
    - pytest-astropy
    - pytest-mock
    - pytest-mpl

about:
  home: https://www.sunpy.org/
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: SunPy core package - sunpy is a software library that provides fundamental tools for accessing, loading and interacting with solar physics data in Python
  license_family: BSD
  dev_url: https://github.com/sunpy/sunpy

extra:
  recipe-maintainers:
    - nabobalis
    - cadair
    - wtbarnes
