{% set name = "sunpy" %}
{% set version = "6.1.0" %}
{% set sha256 = "fecd0625183ffe752652fbf03a4171f71f93ab22158486182dac5c3dc9f8c8ba" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<311]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}  # [not win]
    - {{ stdlib("c") }}    # [not win]
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - extension-helpers
    - numpy
  run:
    - python
    - sqlite!=3.49.0,!=3.49.1  # https://github.com/conda-forge/sqlite-feedstock/issues/130
    # base
    - astropy-base >=6.0.0
    - numpy >=1.24.0
    - packaging >=23.0
    - parfive >=2.0.0
    - pyerfa >=2.0.1.1
    # asdf
    - asdf >=2.13.0
    - asdf-astropy >=0.5.0
    # image
    - scipy >=1.10.1
    # jpeg2000
    - glymur >=0.11.0
    - lxml >=4.9.1,!=5.0.0
    # map
    - contourpy >=1.0.1
    - matplotlib-base >=3.6.0
    - mpl_animators >=1.0.0
    - reproject >=0.10.0
    # net
    - beautifulsoup4 >=4.11.0
    - drms >=0.7.1
    - python-dateutil >=2.8.1
    - tqdm >=4.64.0
    - zeep >=4.1.0
    # spice
    - spiceypy >=5.0.0
    # timeseries
    - cdflib >=1.3.2
    - h5netcdf >=1.0.0
    - h5py >=3.8.0 # Not a direct dependancy, but goes files wont load without
    - pandas >=1.5.0

test:
  requires:
    - hvpy
    - hypothesis
    - jplephem
    - scikit-image
    - libopencv *=headless*               # [unix]
    - opencv
    - pytest-astropy
    - pytest-mock
    - pytest-mpl
    - pytest-xdist

about:
  home: https://www.sunpy.org/
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: SunPy core package - sunpy is a software library that provides fundamental tools for accessing, loading and interacting with solar physics data in Python
  license_family: BSD
  dev_url: https://github.com/sunpy/sunpy

extra:
  recipe-maintainers:
    - cadair
    - wtbarnes
