{% set version = "0.9.10sha" %}

package:
  name: sunpy
  version: {{version}}

source:
  fn: sunpy-{{version}}.tar.gz
  url: https://pypi.io/packages/source/s/sunpy/sunpy-{{ version }}.tar.gz
  sha256: 64922ad93635890ca5fda2743c6f8561829bf792bf8c767fd586020e799ca366

build:
  number: 0
  script: python setup.py install --offline --no-git --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{compiler('c')}}  # [not win]
  host:
    - python
    - setuptools
    - numpy >=1.11,!=1.14.0,!=1.15.3
    - astropy >=2.0.3
    - scipy
    - matplotlib >=1.3
    - pandas >=0.12.1
  run:
    - python
    - numpy >=1.11,!=1.14.0,!=1.15.3
    - astropy >=2.0.3
    - scipy
    - pandas >=0.12.1
    - matplotlib >=1.3
    - suds-jurko
    - glymur
    - sqlalchemy
    - beautifulsoup4
    - requests
    - scikit-image
    - drms

test:
  requires:
    - pytest <3.7  # [py27]
    - pytest  # [py>=35]
    - hypothesis
    - python-dateutil
    - mock
    - pytest-mock
    - pytest-astropy
  imports:
    - sunpy
    - sunpy.cm
    - sunpy.coordinates
    - sunpy.data
    - sunpy.database
    - sunpy.image
    - sunpy.instr
    - sunpy.instr.iris
    - sunpy.io
    - sunpy.lightcurve
    - sunpy.lightcurve.sources
    - sunpy.map
    - sunpy.map.sources
    - sunpy.net
    - sunpy.net.hek
    - sunpy.net.hek2vso
    - sunpy.net.helio
    - sunpy.net.jsoc
    - sunpy.net.vso
    - sunpy.physics
    - sunpy.physics.transforms
    - sunpy.roi
    - sunpy.spectra
    - sunpy.spectra.sources
    - sunpy.sun
    - sunpy.tests
    - sunpy.time
    - sunpy.util
    - sunpy.visualization
    - sunpy.wcs
  commands:
    - python -c "import sunpy, sys; sys.exit(sunpy.self_test())"

about:
  home: https://www.sunpy.org/
  license:  BSD 2-Clause
  summary: "SunPy is an open-source Python library for Solar Physics data analysis and visualization."

extra:
  recipe-maintainers:
    - cadair
    - ehsteve
    - nabobalis
