{% set name = "sunpy" %}
{% set version = "2.0.1" %}
{% set sha256 = "0d0e8f76a2b31c900ccfc7a65165620cdbd85b8a390dc251f04c363d6186d647" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
  host:
    - python
    - pip
    - setuptools_scm
    - extension-helpers
    - numpy
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - astropy >=3.1
    - scipy
    - matplotlib-base >=1.3
    - pandas
    - parfive
    - sqlalchemy
    - scikit-image
    - glymur
    - beautifulsoup4
    - drms
    - python-dateutil
    - zeep
    - tqdm

test:
  requires:
    - hypothesis
    - pytest-astropy
    - pytest-mock
    - asdf
  imports:
    - sunpy
    - sunpy.cm
    - sunpy.coordinates
    - sunpy.data
    - sunpy.database
    - sunpy.image
    - sunpy.instr
    - sunpy.io
    - sunpy.map
    - sunpy.map.sources
    - sunpy.net
    - sunpy.net.hek
    - sunpy.net.hek2vso
    - sunpy.net.helio
    - sunpy.net.jsoc
    - sunpy.net.vso
    - sunpy.physics
    - sunpy.roi
    - sunpy.sun
    - sunpy.tests
    - sunpy.time
    - sunpy.timeseries
    - sunpy.timeseries.sources
    - sunpy.util
    - sunpy.visualization

  commands:
    - python -c "import sunpy, sys; sys.exit(sunpy.self_test())"

about:
  home: https://www.sunpy.org/
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: SunPy is an open-source Python library for Solar Physics data analysis and visualization.
  license_family: BSD
  dev_url: https://github.com/sunpy/sunpy

extra:
  recipe-maintainers:
    - cadair
    - ehsteve
    - wtbarnes
