{% set name = "sunpy" %}
{% set version = "3.0.6" %}
{% set sha256 = "f3a59aa86fc5e68bead1ce56a13fe322879958ed3c07277725017890fd58f5b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
  host:
    - python
    - pip
    - setuptools_scm
    - extension-helpers
    - numpy
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - astropy >=4.1.0
    - scipy >=1.3.0
    - matplotlib-base >=3.1.0
    - pandas >=0.24.0
    - parfive >=1.2.0
    - sqlalchemy >=1.3.4
    - scikit-image >=0.16.0,<0.19
    - glymur >=0.8.18,!=0.9.0
    - beautifulsoup4 >=4.8.0
    - drms >=0.6.1
    - python-dateutil >=2.8.0
    - zeep >=3.4.0
    - tqdm >=4.32.1
    - h5netcdf >=0.8.1
    - h5py >=3.1.0 # Not a direct dependancy, but goes files wont load without

test:
  requires:
    - hypothesis
    - pytest-astropy
    - pytest-mock
    - asdf
    - jplephem
    - pytest-mpl
    - reproject
    - cdflib
  imports:
    - sunpy
    - sunpy.cm
    - sunpy.coordinates
    - sunpy.data
    - sunpy.database
    - sunpy.image
    - sunpy.instr
    - sunpy.io
    - sunpy.map
    - sunpy.map.sources
    - sunpy.net
    - sunpy.net.hek
    - sunpy.net.hek2vso
    - sunpy.net.helio
    - sunpy.net.jsoc
    - sunpy.net.vso
    - sunpy.physics
    - sunpy.roi
    - sunpy.sun
    - sunpy.tests
    - sunpy.time
    - sunpy.timeseries
    - sunpy.timeseries.sources
    - sunpy.util
    - sunpy.visualization

about:
  home: https://www.sunpy.org/
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: SunPy is an open-source Python library for Solar Physics data analysis and visualization.
  license_family: BSD
  dev_url: https://github.com/sunpy/sunpy

extra:
  recipe-maintainers:
    - cadair
    - ehsteve
    - wtbarnes
