{% set version = "0.9.3" %}

package:
  name: sunpy
  version: {{version}}

source:
  fn: sunpy-{{version}}.tar.gz
  url: https://pypi.io/packages/source/s/sunpy/sunpy-{{ version }}.tar.gz
  sha256: 1e7bb32d0851c1e01f202a80f1c35e16618b6c21325ff1fb28cfe138e658c42c

build:
  number: 1000
  script: python setup.py install --offline --no-git --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.11|!=1.14.0  # [py27]
    - numpy >=1.11  # [not py27]
    - astropy >=2.0.3
    - scipy
    - matplotlib
    - pandas
    - mock

  run:
    - python
    - numpy >=1.11|!=1.14.0  # [py27]
    - numpy >=1.11  # [not py27]
    - astropy >=2.0.3
    - scipy
    - pandas >=0.12.1
    - matplotlib >=1.3
    - suds-jurko
    - glymur
    - sqlalchemy
    - beautifulsoup4
    - requests
    - bsddb  # [unix and py27]
    - pytest
    - hypothesis
    - mock
    - pytest-mock
    - pytest-astropy
    - scikit-image
    - drms
    - pillow >=5.2.0

test:
  imports:
    - sunpy
    - sunpy.cm
    - sunpy.coordinates
    - sunpy.data
    - sunpy.data.test
    - sunpy.data.test.waveunit
    - sunpy.database
    - sunpy.database.tests
    - sunpy.image
    - sunpy.image.tests
    - sunpy.instr
    - sunpy.instr.iris
    - sunpy.io
    - sunpy.io.tests
    - sunpy.lightcurve
    - sunpy.lightcurve.sources
    - sunpy.lightcurve.tests
    - sunpy.map
    - sunpy.map.sources
    - sunpy.map.tests
    - sunpy.net
    - sunpy.net.hek
    - sunpy.net.hek2vso
    - sunpy.net.helio
    - sunpy.net.jsoc
    - sunpy.net.tests
    - sunpy.net.vso
    - sunpy.physics
    - sunpy.physics.transforms
    - sunpy.roi
    - sunpy.spectra
    - sunpy.spectra.sources
    - sunpy.spectra.tests
    - sunpy.sun
    - sunpy.sun.tests
    - sunpy.tests
    - sunpy.tests.tests
    - sunpy.time
    - sunpy.time.tests
    - sunpy.util
    - sunpy.util.tests
    - sunpy.visualization
    - sunpy.wcs
    - sunpy.wcs.tests
  commands:
    - python -c "import sunpy, sys; sys.exit(sunpy.self_test())"

about:
  home: http://www.sunpy.org/
  license:  BSD 2-Clause
  summary: "Python for Solar Physics"

extra:
  recipe-maintainers:
    - cadair
    - ehsteve
    - nabobalis
