{% set name = "sunpy" %}
{% set version = "2.1.5" %}
{% set sha256 = "df46101107b248577483d88e547badfc041dcbf6932bdc82004c4b3ee958baff" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
  host:
    - python
    - pip
    - setuptools_scm
    - extension-helpers
    - numpy
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - astropy >=4.0.3
    - scipy >=1.2.0
    - matplotlib-base >=2.2.2
    - pandas >=0.24.0
    - parfive >=1.1.0
    - sqlalchemy
    - scikit-image
    - glymur
    - beautifulsoup4
    - drms >=0.6.1
    - python-dateutil
    - zeep
    - tqdm
    - h5netcdf >=0.8.1

test:
  requires:
    - hypothesis
    - pytest-astropy
    - pytest-mock
    - asdf
  imports:
    - sunpy
    - sunpy.cm
    - sunpy.coordinates
    - sunpy.data
    - sunpy.database
    - sunpy.image
    - sunpy.instr
    - sunpy.io
    - sunpy.map
    - sunpy.map.sources
    - sunpy.net
    - sunpy.net.hek
    - sunpy.net.hek2vso
    - sunpy.net.helio
    - sunpy.net.jsoc
    - sunpy.net.vso
    - sunpy.physics
    - sunpy.roi
    - sunpy.sun
    - sunpy.tests
    - sunpy.time
    - sunpy.timeseries
    - sunpy.timeseries.sources
    - sunpy.util
    - sunpy.visualization

about:
  home: https://www.sunpy.org/
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: SunPy is an open-source Python library for Solar Physics data analysis and visualization.
  license_family: BSD
  dev_url: https://github.com/sunpy/sunpy

extra:
  recipe-maintainers:
    - cadair
    - ehsteve
    - wtbarnes
