{% set version = "1.0.4" %}

package:
  name: sunpy
  version: {{version}}

source:
  fn: sunpy-{{version}}.tar.gz
  url: https://pypi.io/packages/source/s/sunpy/sunpy-{{ version }}.tar.gz
  sha256: 5e5cb4ac7b8ab2612b4bd680bdd4d191917edf6160f78e83f5daeab60ba857b6

build:
  number: 0
  script: python setup.py install --offline --no-git --single-version-externally-managed --record record.txt
  skip: true  # [py<36]
  
requirements:
  build:
    - {{compiler('c')}}  # [not win]
  host:
    - python
    - setuptools_scm
    - numpy >=1.14.5
  run:
    - python
    - setuptools
    - numpy >=1.14.5
    - astropy >=3.1
    - scipy
    - matplotlib >=1.3
    - pandas
    - parfive
    - sqlalchemy
    - scikit-image
    - glymur
    - beautifulsoup4
    - drms
    - python-dateutil
    - zeep
    - tqdm

test:
  requires:
    - hypothesis
    - pytest-astropy
    - pytest-mock
    - jsonschema >=2.3,<=2.6
    - asdf
  imports:
    - sunpy
    - sunpy.cm
    - sunpy.coordinates
    - sunpy.data
    - sunpy.database
    - sunpy.image
    - sunpy.instr
    - sunpy.io
    - sunpy.map
    - sunpy.map.sources
    - sunpy.net
    - sunpy.net.hek
    - sunpy.net.hek2vso
    - sunpy.net.helio
    - sunpy.net.jsoc
    - sunpy.net.vso
    - sunpy.physics
    - sunpy.roi
    - sunpy.sun
    - sunpy.tests
    - sunpy.time
    - sunpy.timeseries
    - sunpy.timeseries.sources
    - sunpy.util
    - sunpy.visualization

  commands:
    - python -c "import sunpy, sys; sys.exit(sunpy.self_test())"

about:
  home: https://www.sunpy.org/
  license:  BSD 2-Clause
  summary: "SunPy is an open-source Python library for Solar Physics data analysis and visualization."

extra:
  recipe-maintainers:
    - cadair
    - ehsteve
    - nabobalis
