{% set name = "sunpy" %}
{% set version = "6.0.0rc1.post1" %}
{% set sha256 = "d172801de81fa7a41126a806ad29e29d7d9b23ad73e9b706f7ce77d88f2d52a7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}  # [not win]
    - {{ stdlib("c") }}    # [not win]
  host:
    - python
    - pip
    - setuptools_scm
    - extension-helpers
    - numpy
  run:
    - python
    # base
    - astropy >=5.2.0
    - packaging >=21.3
    - parfive >=2.0.0
    - pyerfa >=2.0
    # asdf
    - asdf >=2.12.0
    - asdf-astropy >=0.2.0
    # image
    - scipy >=1.7.0,!=1.10.0
    # jpeg2000
    - glymur >=0.9.1,!=0.9.5
    - lxml >=4.9.0,!=5.0.0
    # map
    - matplotlib-base >=3.5.0
    - mpl_animators >=1.0.0
    - reproject >=0.9.0
    # net
    - beautifulsoup4 >=4.11.0
    - drms >=0.7.1
    - python-dateutil >=2.8.0
    - tqdm >=4.64.0
    - zeep >=4.1.0
    # spice
    - spiceypy >=5.0.0
    # timeseries
    - cdflib >=0.4.4,!=1.0.0
    - h5netcdf >=1.0.0
    - h5py >=3.7.0 # Not a direct dependancy, but goes files wont load without
    - pandas >=1.4.0

test:
  requires:
    - hvpy
    - hypothesis
    - jplephem
    - scikit-image
    - libopencv *=headless*               # [unix]
    - opencv
    - pytest-astropy
    - pytest-mock
    - pytest-mpl
    - pytest-xdist

about:
  home: https://www.sunpy.org/
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: SunPy core package - Python for Solar Physics
  license_family: BSD
  dev_url: https://github.com/sunpy/sunpy

extra:
  recipe-maintainers:
    - cadair
    - wtbarnes
    - nabobalis
